name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      testing_choice:
        description: 'Run tests without the integration marker?'
        required: true
        default: "non_integration"
        type: choice
        options:
          - "non_integration"
          - "integration"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.14", "3.8.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup_env
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python version
        run: pytest -v tests/test_python_version.py
      - name: Download books
        run: |
          make get_texts
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.testing_choice }}" == "non_integration" ]; then
            make test
          else
            make test_integration
          fi
